/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}"
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "admin-surface": "#121419",
        "admin-surface-dim": "#0a0b0e",
        "admin-surface-bright": "#1a1d24",
        "admin-surface-container-lowest": "#000000",
        "admin-surface-container-low": "#16191f",
        "admin-surface-container": "#1b1e26",
        "admin-surface-container-high": "#232731",
        "admin-surface-container-highest": "#2a2f3a",
        "admin-on-surface": "#f1f3f9",
        "admin-on-surface-variant": "#8b92a5",
        "admin-inverse-surface": "#f1f3f9",
        "admin-inverse-on-surface": "#121419",
        "admin-outline": "#4b5063",
        "admin-outline-variant": "#2b2f3a",
        "admin-surface-tint": "#3b82f6",
        "admin-primary": "#3b82f6",
        "admin-on-primary": "#ffffff",
        "admin-primary-container": "#1d4ed8",
        "admin-on-primary-container": "#eff6ff",
        "admin-inverse-primary": "#2563eb",
        "admin-secondary": "#10b981",
        "admin-on-secondary": "#ffffff",
        "admin-secondary-container": "#047857",
        "admin-on-secondary-container": "#ecfdf5",
        "admin-tertiary": "#f59e0b",
        "admin-on-tertiary": "#ffffff",
        "admin-tertiary-container": "#b45309",
        "admin-on-tertiary-container": "#fffbeb",
        "admin-error": "#ef4444",
        "admin-on-error": "#ffffff",
        "admin-error-container": "#b91c1c",
        "admin-on-error-container": "#fef2f2",
        "admin-background": "#121419",
        "admin-on-background": "#f1f3f9",
        "on-tertiary-fixed": "#31111d",
        "on-secondary": "#ffffff",
        "on-background": "#1c1b1f",
        "on-tertiary-fixed-variant": "#633b48",
        "surface-variant": "#e7e0ec",
        "error": "#b3261e",
        "inverse-on-surface": "#f4eff4",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#2a007a",
        "secondary-fixed-dim": "#ccc2dc",
        "tertiary-container": "#ffd8e4",
        "tertiary-fixed": "#ffd8e4",
        "on-secondary-fixed": "#1d192b",
        "on-error-container": "#410e0b",
        "on-secondary-container": "#1d192b",
        "secondary-container": "#e8def8",
        "surface-container-high": "#ece6f0",
        "error-container": "#f9dedc",
        "primary-fixed": "#f0e5ff",
        "on-error": "#ffffff",
        "on-surface": "#1c1b1f",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#4d00d2",
        "tertiary-fixed-dim": "#efb8c8",
        "on-tertiary-container": "#31111d",
        "secondary": "#625b71",
        "tertiary": "#7d5260",
        "inverse-primary": "#ccbdff",
        "on-secondary-fixed-variant": "#4a4458",
        "surface-container-lowest": "#ffffff",
        "background": "#ffffff",
        "outline-variant": "#cac4d0",
        "outline": "#79747e",
        "on-surface-variant": "#49454f",
        "primary": "#a87ffb",
        "surface-dim": "#ded8e1",
        "on-primary-fixed": "#2a007a",
        "surface-container-highest": "#e6e0e9",
        "surface": "#fdfcff",
        "secondary-fixed": "#e8def8",
        "surface-tint": "#a87ffb",
        "surface-bright": "#fdfcff",
        "surface-container": "#f3edf7",
        "primary-fixed-dim": "#d3bfff",
        "surface-container-low": "#f7f2fa",
        "inverse-surface": "#313033",
        "primary-container": "#f0e5ff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "xs": "4px",
        "xl": "40px",
        "md": "16px",
        "sm": "8px",
        "gutter": "24px",
        "margin-desktop": "48px",
        "unit": "4px",
        "margin-mobile": "16px",
        "lg": "24px"
      },
      "fontFamily": {
        "body-lg": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"]
      },
      "fontSize": {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "16px", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "60px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
